{{ if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: datalens-pg-cip
spec:
  selector:
    app: datalens-app-pg
  ports:
  - protocol: TCP
    port: 5432
  clusterIP: None
{{ end }}
