apiVersion: v1
kind: Service
metadata:
  name: datalens-ui-cip
spec:
  selector:
    app: datalens-app-ui
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
