{{ if and .Values.database.enabled .Values.database.demo }}
# service only for datalens demo data connection
apiVersion: v1
kind: Service
metadata:
  name: pg-demo-connection
spec:
  selector:
    app: datalens-app-pg
  ports:
  - protocol: TCP
    port: 5432
  clusterIP: None
{{ end }}
