#cloud-config
runcmd:
  - apt update && apt install -y jq unzip curl wget git docker.io docker-compose-v2
  # install github cli
  - mkdir -p -m 755 /etc/apt/keyrings
  - wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null
  - chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
  - apt update && apt install gh -y
  # install yc cli
  - su - root -c "curl -o ./yc-install.sh -L https://storage.yandexcloud.net/yandexcloud-yc/install.sh"
  - su - root -c "chmod +x ./yc-install.sh && ./yc-install.sh -i /tmp/yc -n && mv /tmp/yc/bin/yc /usr/bin/yc"
  # add non root user
  - useradd -m github --shell /bin/bash && usermod -aG docker github
  - cd /home/github
  - su - github -c "mkdir -p /home/github/actions-runner"
  - cd actions-runner
  # install github runner agent
  - case $(uname -m) in aarch64) ARCH="arm64" ;; amd64|x86_64) ARCH="x64" ;; esac && export RUNNER_ARCH=$${ARCH}
  - export RUNNER_TOKEN=$(yc lockbox payload get --id ${LOCKBOX_ID} --key ${LOCKBOX_KEY})
  - su - github -c "curl -O -L https://github.com/actions/runner/releases/download/v${VERSION}/actions-runner-linux-$${RUNNER_ARCH}-${VERSION}.tar.gz"
  - su - github -c "tar xzf ./actions-runner-linux-$${RUNNER_ARCH}-${VERSION}.tar.gz"
  - su - github -c "./config.sh --unattended --url https://github.com/${OWNER}/${REPO} --token $${RUNNER_TOKEN} --name github-runner-${REPO}-ind-${IND} --runnergroup default --work _work --labels cloud"
  - su - root -c "./svc.sh install github"
  - su - root -c "./svc.sh start"
