apiVersion: apps/v1
kind: Deployment
metadata:
  name: datalens-us
  namespace: {{ .Release.Namespace }}
  labels:
    app: app-us
spec:
  replicas: {{ .Values.application.us.replicas }}
  selector:
    matchLabels:
      app: app-us
  template:
    metadata:
      labels:
        app: app-us
    spec:
      containers:
        - name: app-us
          image: "{{ .Values.registry.url }}/datalens-us:{{ .Values.application.us.version }}"
          ports:
            - containerPort: 8080
          env:
            - name: APP_INSTALLATION
              value: opensource
            - name: APP_ENV
              value: prod
            - name: APP_PORT
              value: '8080'
            - name: SKIP_INSTALL_DB_EXTENSIONS
              value: '1'
            - name: USE_DEMO_DATA
              value: '0'
            {{- if .Values.features.hc.enabled }}
            - name: HC
              value: '1'
            {{- end }}
            - name: MASTER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ default "datalens-secrets" .Values.secrets.ref }}
                  key: US_MASTER_TOKEN
            - name: POSTGRES_DSN_LIST
              valueFrom:
                secretKeyRef:
                  name: {{ default "datalens-secrets" .Values.secrets.ref }}
                  key: POSTGRES_DSN_LIST_US
            {{- if and .Values.features.auth.enabled }}
            - name: AUTH_ENABLED
              value: 'true'
            - name: AUTH_MASTER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ default "datalens-secrets" .Values.secrets.ref }}
                  key: AUTH_MASTER_TOKEN
            - name: AUTH_TOKEN_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ default "datalens-secrets" .Values.secrets.ref }}
                  key: AUTH_TOKEN_PUBLIC_KEY
            {{- end }}
          {{- if and .Values.infra.postgres.tls.enabled (or .Values.infra.postgres.tls.secret.ref .Values.infra.postgres.tls.secret.ca) }}
          volumeMounts:
          - name: postgres-tls
            mountPath: /certs/postgres-ca.crt
            subPath: ca.crt
            readOnly: true
          {{- end }}
          resources:
            requests:
              cpu: {{ .Values.application.us.resources.requests.cpu }}
              memory: {{ .Values.application.us.resources.requests.memory }}
            limits:
              {{- if .Values.application.us.resources.limits.cpu }}
              cpu: {{ .Values.application.us.resources.limits.cpu }}
              {{- end }}
              memory: {{ .Values.application.us.resources.limits.memory }}
      {{- if and .Values.infra.postgres.tls.enabled (or .Values.infra.postgres.tls.secret.ref .Values.infra.postgres.tls.secret.ca) }}
      volumes:
        - name: postgres-tls
          secret:
            secretName: {{ default "postgres-tls-secret" .Values.infra.postgres.tls.secret.ref }}
      {{- end }}
