apiVersion: apps/v1
kind: Deployment
metadata:
  name: datalens-auth
  namespace: {{ .Release.Namespace }}
  labels:
    app: app-auth
spec:
  replicas: {{ .Values.application.auth.replicas }}
  selector:
    matchLabels:
      app: app-auth
  template:
    metadata:
      labels:
        app: app-auth
    spec:
      containers:
        - name: app-auth
          image: "{{ .Values.registry.url }}/datalens-auth:{{ .Values.application.auth.version }}"
          ports:
            - containerPort: 8080
          env:
            - name: APP_INSTALLATION
              value: opensource
            - name: APP_ENV
              value: prod
            - name: SKIP_INSTALL_DB_EXTENSIONS
              value: '1'
            - name: UI_APP_ENDPOINT
            {{- if and .Values.ingress.tls.enabled .Values.ingress.domain }}
              value: "https://{{ .Values.ingress.domain }}"
            {{- else if .Values.ingress.domain }}
              value: "http://{{ .Values.ingress.domain }}"
            {{- else if .Values.ingress.ip }}
              value: "http://{{ .Values.ingress.ip }}"
            {{- end }}
            - name: US_ENDPOINT
              value: http://app-us-cip:8080
            - name: TOKEN_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ default "datalens-secrets" .Values.secrets.ref }}
                  key: AUTH_TOKEN_PRIVATE_KEY
            - name: TOKEN_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ default "datalens-secrets" .Values.secrets.ref }}
                  key: AUTH_TOKEN_PUBLIC_KEY
            - name: AUTH_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default "datalens-secrets" .Values.secrets.ref }}
                  key: AUTH_ADMIN_PASSWORD
            - name: MASTER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ default "datalens-secrets" .Values.secrets.ref }}
                  key: AUTH_MASTER_TOKEN
            - name: US_MASTER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ default "datalens-secrets" .Values.secrets.ref }}
                  key: US_MASTER_TOKEN
            - name: POSTGRES_DSN_LIST
              valueFrom:
                secretKeyRef:
                  name: {{ default "datalens-secrets" .Values.secrets.ref }}
                  key: POSTGRES_DSN_LIST_AUTH
          resources:
            requests:
              cpu: {{ .Values.application.auth.resources.requests.cpu }}
              memory: {{ .Values.application.auth.resources.requests.memory }}
            limits:
              memory: {{ .Values.application.auth.resources.limits.memory }}
