{{- $US_MASTER_TOKEN := .Values.secrets.US_MASTER_TOKEN | default (randAlphaNum 32) }}
{{- $AUTH_MASTER_TOKEN := .Values.secrets.AUTH_MASTER_TOKEN | default (randAlphaNum 32) }}
{{- $CONTROL_API_CRYPTO_KEY := .Values.secrets.CONTROL_API_CRYPTO_KEY | default (randAlphaNum 32 | b64enc) }}

{{- $CERT := dict "Cert" "" "Key" "" }}
{{ if and .Values.ingress.enabled .Values.ingress.domain }}
  {{- $CERT = genSelfSignedCert .Values.ingress.domain nil nil 365 | toJson | fromJson }}
{{ end }}

{{- $INGRESS_TLS_CRT := .Values.ingress.tls.secret.crt | default (get $CERT "Cert") }}
{{- $INGRESS_TLS_KEY := .Values.ingress.tls.secret.key | default (get $CERT "Key") }}

{{- $POSTGRES_PASSWORD := .Values.secrets.POSTGRES_PASSWORD | default (randAlphaNum 32)}}

{{- $AUTH_TOKEN_PRIVATE_KEY := .Values.secrets.AUTH_TOKEN_PRIVATE_KEY | default ""}}
{{- $AUTH_TOKEN_PUBLIC_KEY := .Values.secrets.AUTH_TOKEN_PUBLIC_KEY | default ""}}
{{- $AUTH_ADMIN_PASSWORD := .Values.secrets.AUTH_ADMIN_PASSWORD | default (randAlphaNum 32)}}

{{- $DICT := dict "__" "__" }}
{{- $SECRET := (lookup "v1" "Secret" .Release.Namespace "datalens-secrets").data | default $DICT }}

{{- $US_MASTER_TOKEN := get $SECRET "US_MASTER_TOKEN" | default ($US_MASTER_TOKEN | b64enc) }}
{{- $AUTH_MASTER_TOKEN := get $SECRET "AUTH_MASTER_TOKEN" | default ($AUTH_MASTER_TOKEN | b64enc) }}
{{- $CONTROL_API_CRYPTO_KEY := get $SECRET "CONTROL_API_CRYPTO_KEY" | default ($CONTROL_API_CRYPTO_KEY | b64enc) }}
{{- $AUTH_ADMIN_PASSWORD := get $SECRET "AUTH_ADMIN_PASSWORD" | default ($AUTH_ADMIN_PASSWORD | b64enc) }}

{{ if .Values.secrets.AUTH_TOKEN_PRIVATE_KEY }}
  {{- $AUTH_TOKEN_PRIVATE_KEY = $AUTH_TOKEN_PRIVATE_KEY | b64enc }}
{{ else }}
  {{- $AUTH_TOKEN_PRIVATE_KEY = get $SECRET "AUTH_TOKEN_PRIVATE_KEY" | default ($AUTH_TOKEN_PRIVATE_KEY | b64enc) }}
{{ end }}

{{ if .Values.secrets.AUTH_TOKEN_PUBLIC_KEY }}
  {{- $AUTH_TOKEN_PUBLIC_KEY = $AUTH_TOKEN_PUBLIC_KEY | b64enc }}
{{ else }}
  {{- $AUTH_TOKEN_PUBLIC_KEY = get $SECRET "AUTH_TOKEN_PUBLIC_KEY" | default ($AUTH_TOKEN_PUBLIC_KEY | b64enc) }}
{{ end }}

{{ if .Values.ingress.tls.secret.crt }}
  {{- $INGRESS_TLS_CRT = $INGRESS_TLS_CRT | b64enc }}
{{ else }}
  {{- $INGRESS_TLS_CRT = get $SECRET "INGRESS_TLS_CRT" | default ($INGRESS_TLS_CRT | b64enc) }}
{{ end }}

{{ if .Values.ingress.tls.secret.key }}
  {{- $INGRESS_TLS_KEY = $INGRESS_TLS_KEY | b64enc }}
{{ else }}
  {{- $INGRESS_TLS_KEY = get $SECRET "INGRESS_TLS_KEY" | default ($INGRESS_TLS_KEY | b64enc) }}
{{ end }}

{{ if .Values.secrets.POSTGRES_PASSWORD }}
  {{- $POSTGRES_PASSWORD = $POSTGRES_PASSWORD | b64enc }}
{{ else }}
  {{- $POSTGRES_PASSWORD = get $SECRET "POSTGRES_PASSWORD" | default ($POSTGRES_PASSWORD | b64enc) }}
{{ end }}
{{- if not .Values.secrets.ref }}
---
apiVersion: v1
kind: Secret
metadata:
  name: datalens-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  AUTH_TOKEN_PRIVATE_KEY: {{ $AUTH_TOKEN_PRIVATE_KEY }}
  AUTH_TOKEN_PUBLIC_KEY: {{ $AUTH_TOKEN_PUBLIC_KEY }}

  AUTH_MASTER_TOKEN: {{ $AUTH_MASTER_TOKEN }}
  US_MASTER_TOKEN: {{ $US_MASTER_TOKEN }}
  CONTROL_API_CRYPTO_KEY: {{ $CONTROL_API_CRYPTO_KEY }}

  AUTH_ADMIN_PASSWORD: {{ $AUTH_ADMIN_PASSWORD }}

  INGRESS_TLS_CRT: {{ $INGRESS_TLS_CRT }}
  INGRESS_TLS_KEY: {{ $INGRESS_TLS_KEY }}

  POSTGRES_PASSWORD: {{ $POSTGRES_PASSWORD }}

  POSTGRES_DSN_LIST_COMPENG: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.postgres.POSTGRES_USER ($POSTGRES_PASSWORD | b64dec) .Values.postgres.POSTGRES_HOST .Values.postgres.POSTGRES_PORT .Values.postgres.POSTGRES_DB_COMPENG | b64enc}}
  POSTGRES_DSN_LIST_US: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.postgres.POSTGRES_USER ($POSTGRES_PASSWORD | b64dec) .Values.postgres.POSTGRES_HOST .Values.postgres.POSTGRES_PORT .Values.postgres.POSTGRES_DB_US | b64enc}}
  POSTGRES_DSN_LIST_AUTH: {{ printf "postgres://%s:%s@%s:%s/%s" .Values.postgres.POSTGRES_USER ($POSTGRES_PASSWORD | b64dec) .Values.postgres.POSTGRES_HOST .Values.postgres.POSTGRES_PORT .Values.postgres.POSTGRES_DB_AUTH | b64enc}}
{{- end }}
{{- if and .Values.ingress.tls.enabled $INGRESS_TLS_CRT $INGRESS_TLS_KEY (not .Values.ingress.tls.secret.ref) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-tls-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
type: kubernetes.io/tls
data:
  tls.crt: {{ $INGRESS_TLS_CRT }}
  tls.key: {{ $INGRESS_TLS_KEY }}
{{- end }}
