apiVersion: v1
kind: Service
metadata:
  name: app-ui-service
spec:
  selector:
    app: app-ui
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
{{ if .Values.ingress.np }}
    nodePort: 31080
  type: NodePort
{{ else }}
  type: ClusterIP
{{ end }}
