{{ if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: datalens-postgres-cip
spec:
  selector:
    app: datalens-postgres
  ports:
  - protocol: TCP
    port: 5432
  clusterIP: None
{{ end }}
