{{- if .Values.infra.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datalens-postgres-volume
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: {{ .Values.infra.postgres.resources.requests.storage }}
    limits:
      storage: {{ .Values.infra.postgres.resources.limits.storage }}
{{- end }}
