ARG image=ubuntu:24.04
FROM ${image}

ARG USER=app

USER root
RUN apt-get update && \
  apt-get -y install build-essential g++ make nodejs

RUN chown -R ${USER}:${USER} /opt/${USER}

RUN npm install -g pnpm@10.17.1

USER ${USER}

COPY ./entrypoint.sh /opt/dev/entrypoint.sh
COPY ./dev-entry.js /opt/dev/dev-entry.js

ENTRYPOINT [ "/opt/dev/entrypoint.sh" ]
