ARG image=ubuntu:24.04
FROM ${image}

ARG USER=app
ARG PNPM_VERSION=10.17.1

USER root
RUN apt-get update && \
  apt-get -y install build-essential g++ make nodejs

RUN npm install -g pnpm@${PNPM_VERSION}

RUN id -u ${USER} &>/dev/null || useradd -m -u 1001 ${USER}

RUN rm -rf /opt/${USER} && mkdir -p /opt/${USER} && chown -R ${USER}:${USER} /opt/${USER}

RUN mkdir -p /opt/${USER}/.pnpm-store && chown ${USER}:${USER} /opt/${USER}/.pnpm-store
RUN mkdir -p /opt/${USER}/node_modules && chown ${USER}:${USER} /opt/${USER}/node_modules

USER ${USER}

COPY ./entrypoint.sh /opt/dev/entrypoint.sh
COPY ./dev-entry.js /opt/dev/dev-entry.js

ENTRYPOINT [ "/opt/dev/entrypoint.sh" ]
