FROM alpine:3.19

ENV PYTHONUNBUFFERED=1

RUN apk add --update --no-cache bash curl python3 py3-cryptography postgresql-client

COPY ./init/ /init/
COPY ./init.sh /init/init.sh
COPY ./crypto.py /init/crypto.py

RUN chmod +x /init/init.sh

WORKDIR /init

ENTRYPOINT [ "./init.sh" ]
