name: Build Docker PostgreSQL

on:
  push:
    branches:
      - main
    paths:
      - 'postgres/*'
  workflow_dispatch:
    inputs:
      pg_version:
        type: string
        default: '16'
        description: 'PostgreSQL main version'
      pg_version_suffix:
        type: string
        default: '0.1.0'
        description: 'Container custom version suffix'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: datalens-tech/datalens-postgres
  POSTGRES_VERSION: ${{ github.event.inputs.pg_version || '16' }}
  POSTGRES_VERSION_SUFFIX: ${{ github.event.inputs.pg_version_suffix || '0.1.0' }}

jobs:
  run:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: 'arm64'
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.POSTGRES_VERSION }}
            type=raw,value=${{ env.POSTGRES_VERSION }}-${{ env.POSTGRES_VERSION_SUFFIX }}
      - uses: docker/build-push-action@v6
        with:
          build-args: |
            POSTGRES_VERSION=${{ env.POSTGRES_VERSION }}
          context: ./postgres
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
