on:
    workflow_dispatch:
    pull_request:
       paths:
        - 'docker-compose*.yml'
    push:
      branches:    
        - main
      paths:
        - 'docker-compose*.yml'
  
name: Check docker-compose for updates

jobs:
    check_modified_compose_files:
        name: check docker-compose files
        runs-on: ubuntu-latest
        steps:
          - run: |
                check_diff() {
                   git diff --name-only main...HEAD | grep -E  'docker-compose[A-Za-z0-9.-]+.yml' | wc -l   
                }
                if check_diff; then
                 exit(0)
                else
                  exit(1)
                fi
                git diff --name-only main...HEAD | grep -E  'docker-compose[A-Za-z0-9.-]+.yml'      
