name: Update version in yaml

on:
  pull_request:
  workflow_call:
    inputs:
      pr_head:
        type: string
  workflow_dispatch:
    inputs:
      pr_head:
        type: string
        description: 'ref hash commit'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  run:
    name: yq
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: '${{ github.event.pull_request.head.ref }}${{ inputs.pr_head }}'
      - uses: frenck/action-setup-yq@v1
      - name: script update-versions
        run: ./scripts/update-versions.sh
      - name: initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: commit changed files
        run: |
          git add docker-compose.yaml
          git add docker-compose.dev.yaml
          git add helm/values.yaml
          git add helm/Chart.yaml
          if ! git diff-index --quiet HEAD; then
              git commit --message "update versions for docker and helm" || exit 0
              git push
          fi
