on:
  pull_request:
    paths:
      - 'templates/**.j2'
      - 'versions-config.json'
  workflow_call:
    inputs:
      pr_head:
        type: string

name: Update docker-compose.yml docker-compose-dev.yml
permissions:
  contents: write

jobs:
  update_compose_files:
    name: build files
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: "${{ github.event.pull_request.head.ref }}${{ inputs.pr_head }}"
          token: ${{ secrets.GH_TOKEN }}
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: install jinja2
        run: |
          pip3 install --user --upgrade j2cli
          j2 --version  
      - name: build docker-compose.yml & docker-compose-dev.yml & docker-compose.zitadel.yml
        run: |
          j2 ./templates/docker-compose.j2 versions-config.json --format=json > ./docker-compose.yml
          DEV_MODE=true j2 ./templates/docker-compose.j2 versions-config.json --format=json > ./docker-compose-dev.yml
          j2 ./templates/docker-compose.zitadel.j2 versions-config.json --format=json > ./docker-compose.zitadel.yml
      - name: check docker-compose.yml config
        run: docker compose -f ./docker-compose.yml config
      - name: Initialize mandatory git config
        run: |
          git config user.email "" && git config user.name "GitHub Action"
      - name: Commit compose files
        id: make-commit
        run: |
            git add docker-compose.yml docker-compose-dev.yml docker-compose.zitadel.yml
            if ! git diff-index --quiet HEAD; then
                git commit --message "update docker-compose.yml docker-compose-dev.yml"
                git push
            fi
