on:
  workflow_dispatch:
  push:
    branches:    
      - main
    paths:
      - 'version-config.json'

name: Update docker-compose
  
jobs:
  update_compose_files:
    name: build files
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build docker-compose.yml
        uses: cuchi/jinja2-action@v1.2.2
        with:
          template: templates/docker-compose.j2
          output_file: ./docker-compose.yml
          data_file: ./versions-config.json
          data_format: json
      - name: build docker-compose-dev.yml
        uses: cuchi/jinja2-action@v1.2.2
        with:
          template: templates/docker-compose-dev.j2
          output_file: ./docker-compose-dev.yml
          data_file: ./versions-config.json
          data_format: json
      - name: Commit and push docker-compose-*.yml
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docker-compose.yml docker-compose-dev.yml'
          message: "chore: Update docker-compose-*.yml"
          committer_name: GitHub Actions
          committer_email: actions@github.com
