ARG TEMPORAL_VERSION=1.27.2

FROM temporalio/auto-setup:${TEMPORAL_VERSION} AS temporal-setup

FROM temporalio/server:${TEMPORAL_VERSION}

USER root

RUN apk add --no-cache postgresql-client openssl

COPY --from=temporal-setup /usr/local/bin/temporal-sql-tool /usr/local/bin/temporal-sql-tool
RUN rm -rf /etc/temporal/schema
COPY --from=temporal-setup /etc/temporal/schema/postgresql/v12/temporal/versioned /etc/temporal/schema/temporal
COPY --from=temporal-setup /etc/temporal/schema/postgresql/v12/visibility/versioned /etc/temporal/schema/visibility

COPY ./setup-temporal.sh /etc/temporal/setup-temporal.sh
COPY ./setup-auth-jwks.sh /etc/temporal/setup-auth-jwks.sh
COPY ./init-namespaces.sh /etc/temporal/init-namespaces.sh
COPY ./init-temporal.sh /etc/temporal/init-temporal.sh
COPY ./healthcheck.sh /etc/temporal/healthcheck.sh

RUN chmod +x /etc/temporal/setup-temporal.sh && \
  chmod +x /etc/temporal/setup-auth-jwks.sh && \
  chmod +x /etc/temporal/init-namespaces.sh && \
  chmod +x /etc/temporal/init-temporal.sh && \
  chmod +x /etc/temporal/healthcheck.sh

USER temporal

ENV TEMPORAL_PORT='7233'

ENV DB='postgres12'

ENV NUM_HISTORY_SHARDS='512'
ENV DEFAULT_NAMESPACE_RETENTION='24h'
ENV SKIP_NAMESPACES_CREATION='false'
ENV NAMESPACES='meta-manager'

ENV POSTGRES_HOST='postgres'
ENV POSTGRES_PORT='5432'
ENV POSTGRES_USER='pg-user'
ENV POSTGRES_DB='pg-temporal-db'
ENV POSTGRES_DB_VISIBILITY='pg-temporal-visibility-db'
ENV POSTGRES_TLS_ENABLED='false'
ENV POSTGRES_TLS_DISABLE_HOST_VERIFICATION='true'
ENV POSTGRES_TLS_CA_FILE=''
ENV POSTGRES_CONNECT_ATTRIBUTES=''

HEALTHCHECK --interval=5s --start-period=5s --retries=10 CMD ["/etc/temporal/healthcheck.sh"]

ENTRYPOINT ["/etc/temporal/init-temporal.sh"]
